#### Embeddings

In [1]:

#Importing OHE
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
#sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am good boy',
      'i am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the Vocabulary size
voc_size = 10000

In [5]:
#One Hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4745, 9808, 831, 1254],
 [4745, 9808, 831, 8513],
 [4745, 8238, 831, 3388],
 [1106, 665, 8917, 5647],
 [1106, 665, 8281, 8917, 2710],
 [687, 4745, 3163, 831, 8683],
 [2178, 7840, 6767, 8917]]

In [6]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

ModuleNotFoundError: No module named 'tensorflow.keras.processing'

In [7]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [10]:
#making all sentences of fixed size
sent_length=8
embedded_pad=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedded_pad

array([[   0,    0,    0,    0, 4745, 9808,  831, 1254],
       [   0,    0,    0,    0, 4745, 9808,  831, 8513],
       [   0,    0,    0,    0, 4745, 8238,  831, 3388],
       [   0,    0,    0,    0, 1106,  665, 8917, 5647],
       [   0,    0,    0, 1106,  665, 8281, 8917, 2710],
       [   0,    0,    0,  687, 4745, 3163,  831, 8683],
       [   0,    0,    0,    0, 2178, 7840, 6767, 8917]])

In [11]:
## Feature Representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_pad)

1/1 [==============================] - 0s 324ms/step


array([[[ 0.03642787, -0.00111867,  0.00716772,  0.03780128,
          0.02046161,  0.01414316, -0.030788  , -0.00081402,
          0.02388098,  0.04479058],
        [ 0.03642787, -0.00111867,  0.00716772,  0.03780128,
          0.02046161,  0.01414316, -0.030788  , -0.00081402,
          0.02388098,  0.04479058],
        [ 0.03642787, -0.00111867,  0.00716772,  0.03780128,
          0.02046161,  0.01414316, -0.030788  , -0.00081402,
          0.02388098,  0.04479058],
        [ 0.03642787, -0.00111867,  0.00716772,  0.03780128,
          0.02046161,  0.01414316, -0.030788  , -0.00081402,
          0.02388098,  0.04479058],
        [ 0.02004122,  0.02396524,  0.03959136,  0.01421844,
         -0.03817099, -0.00477749, -0.00950535,  0.00239419,
         -0.01226754,  0.00090153],
        [-0.00283109,  0.02036307,  0.04540643, -0.00653602,
          0.04665164, -0.03045258, -0.03687053, -0.02539795,
         -0.01582264,  0.0072848 ],
        [-0.01371161, -0.02827547, -0.01202057,  0.0

In [16]:
embedded_pad[0]

array([   0,    0,    0,    0, 4745, 9808,  831, 1254])

In [17]:
model.predict(embedded_pad[0])

1/1 [==============================] - 0s 66ms/step


array([[ 0.03642787, -0.00111867,  0.00716772,  0.03780128,  0.02046161,
         0.01414316, -0.030788  , -0.00081402,  0.02388098,  0.04479058],
       [ 0.03642787, -0.00111867,  0.00716772,  0.03780128,  0.02046161,
         0.01414316, -0.030788  , -0.00081402,  0.02388098,  0.04479058],
       [ 0.03642787, -0.00111867,  0.00716772,  0.03780128,  0.02046161,
         0.01414316, -0.030788  , -0.00081402,  0.02388098,  0.04479058],
       [ 0.03642787, -0.00111867,  0.00716772,  0.03780128,  0.02046161,
         0.01414316, -0.030788  , -0.00081402,  0.02388098,  0.04479058],
       [ 0.02004122,  0.02396524,  0.03959136,  0.01421844, -0.03817099,
        -0.00477749, -0.00950535,  0.00239419, -0.01226754,  0.00090153],
       [-0.00283109,  0.02036307,  0.04540643, -0.00653602,  0.04665164,
        -0.03045258, -0.03687053, -0.02539795, -0.01582264,  0.0072848 ],
       [-0.01371161, -0.02827547, -0.01202057,  0.00267482,  0.03667151,
        -0.01275329, -0.01595012,  0.01865334